import { useContext, useState } from "react";
import { Col, Row, Select } from "antd";
import TransactionTable from "@/components/Table/TransactionTable";
import { TransactionsContext } from "@/contexts/Transactions/TransactionsContext";
import Head from "next/head";

const categories: Transaction["category"][] = [
  "Alimentação",
  "Transporte",
  "Moradia",
  "Lazer",
  "Outros",
];

function TransactionsPage() {
  const { transactions } = useContext(TransactionsContext);
  const [filter, setFilter] = useState<Transaction["category"]>("Todos");

  const filteredTransactions =
    filter === "Todos"
      ? transactions
      : transactions.filter((transaction) => transaction.category === filter);

  return (
    <>
      <Head>
        <title>Transações</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Row gutter={[0, 20]}>
          <Col span={24}>
            <h1>Filtrar por categoria:</h1>
            <Select
              value={filter}
              onChange={(value) => setFilter(value)}
              style={{ width: 200 }}
            >
              <Select.Option value="Todos">Todos</Select.Option>
              {categories.map((category) => (
                <Select.Option key={category} value={category}>
                  {category}
                </Select.Option>
              ))}
            </Select>
          </Col>
          <Col span={24}>
            <TransactionTable filteredTransactions={filteredTransactions} />
          </Col>
        </Row>
    </>
  );
}

export default TransactionsPage;
